DjangoRolApp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic.base import TemplateView 

urlpatterns = [

    path('admin/', admin.site.urls),
    path('potion_craft/', include("potion_craft.urls")),

    #URL DE AUTENTICACIÓN
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    

    path('', TemplateView.as_view(template_name="potion_craft/index.html"), name="index"),
]

accounts/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView 
from . import views
from .views import SignUpView



app_name = "accounts"

#RECUERDA QUE LA PÁGINA DE LOGIN ESTÁ AQUÍ: http://127.0.0.1:8000/accounts/login/
#El login está en ACCOUNTS, y no en la app como tal.

urlpatterns=[
    path('', TemplateView.as_view(template_name="potion_craft/index.html"), name="index"),
    #path("signup/", SignUpView.as_view(), name="signup"),
    path("signup/", views.signup, name="signup"),
    
]

potion_craft/urls.py
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView 
from . import views
from .views import *



app_name = "potion_craft"

#RECUERDA QUE LA PÁGINA DE LOGIN ESTÁ AQUÍ: http://127.0.0.1:8000/accounts/login/
#El login está en ACCOUNTS, y no en la app como tal.

app_name = "potion_craft"

urlpatterns = [
    path("", views.index, name="index"), #Cuando alguien visite la url vacía, verá la index.
    path("craft/", views.ingredient_craft, name="craft"),
    path("potion/", views.potion_craft, name="potion"),
    path('inventario/', views.inventario, name='inventario'),
    path("inventario/<int:personaje_id>", views.inventario_detail, name="inventario_detail"),

    path('character_creator/', views.character_creator, name='character_creator'),
    path('borrar/', views.borrar_datos_sesion, name='borrar'),
    path('admin/', admin.site.urls),
]

potion_craft/models.py
from django.db import models
from accounts.models import UserProfile
#hola

class Personaje(models.Model):
    nombre = models.CharField(max_length = 25, unique=True)
    clase = models.CharField(max_length = 25, null=True, blank=True)
    raza = models.CharField(max_length = 25, null=True, blank=True)
    genero = models.CharField(max_length = 25, null=True, blank=True)
    portrait = models.CharField(max_length = 150, null=True, blank=True)
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE, 
                                     related_name='personajes', null=True, blank=True)
    
    def __str__(self):
        return f"Nombre: {self.nombre}, Clase: {self.nombre}, URL: {self.nombre}, Usuario: {self.user_profile}"


class Esencia(models.Model):
    nombre = models.CharField(max_length=25, default='Esencia')
    tipo = models.CharField(max_length = 25, help_text='aire / agua / fuego / tierra') #elemento
    valor = models.CharField(max_length=25, default='1')
    def __str__(self):
        return f"{self.nombre}, del tipo: {self.tipo} "
    
class Ingrediente(models.Model):
    nombre = models.CharField(max_length = 25)
    descripcion = models.CharField(max_length = 140)
    esencias = models.ManyToManyField(Esencia, related_name="esencias_por_ingredientes")
    def __str__(self):
        return f"{self.nombre}: {self.descripcion}"


class Potion(models.Model):
    nombre = models.CharField(max_length = 25)
    descripcion = models.CharField(max_length = 140)
    esencias = models.ManyToManyField('Esencia', related_name='esencias_por_pocion')
    alteracion = models.CharField(max_length=25, default=None, blank=True, null=True)

    def __str__(self):
        return f"{self.nombre}: {self.descripcion} "


"""Y  A PARTIR DE AQUÍ LAS RELACIONES CON ATRIBUTOOS PARA EXPRESAR LA CANTIDAD"""

class PersonajePotion(models.Model):
    personaje = models.ForeignKey(Personaje, on_delete=models.CASCADE)
    potion = models.ForeignKey(Potion, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

    def __str__(self):
        return f"{self.personaje.nombre} tiene {self.cantidad} unidades de {self.potion.nombre}"
    

class PersonajeEsencias(models.Model):
    personaje = models.ForeignKey(Personaje, on_delete=models.CASCADE)
    esencia = models.ForeignKey(Esencia, on_delete=models.CASCADE)
    cantidad = models.IntegerField(default = 0)
    
    def __str__(self):
        return f"{self.personaje.nombre} tiene {self.cantidad} unidades de {self.esencia.nombre}"
    
class PersonajeIngredientes(models.Model):
    personaje = models.ForeignKey(Personaje, on_delete=models.CASCADE)
    ingrediente = models.ForeignKey(Ingrediente, on_delete=models.CASCADE)
    cantidad = models.IntegerField()

    def __str__(self):
        return f"{self.personaje.nombre} tiene {self.cantidad} unidades de {self.ingrediente.nombre}"

potion_craft/forms.py
# en forms.py
from django import forms
import random
from .models import *


class ReadOnlyIntegerField(forms.IntegerField):
    def __init__(self, initial=None, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.initial = random.randint(1,20)
    def widget_attrs(self, widget):
        attrs = super().widget_attrs(widget)
        attrs['readonly'] = True
        return attrs


#!VERIFICAR QUE ESTÁ BIEN ESTRUCTURADO
class CharacterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['nombre'].widget.attrs.update({
            'placeholder': 'Escribe el nombre de tu pesonaje'
        })

    CLASES = [
        ('guerrero', 'Guerrero'),
        ('mago', 'Mago'),
        ('explorador', 'Explorador'),
        ('clerigo', 'Clérigo'),
        ('bardo', 'Bardo'),
    ]
    IMAGENES = [
    ('potion_craft/img/portraits/Eric.png', 'Imagen 1'),
    ('potion_craft/img/portraits/humano-bardo-3.png', 'Imagen 2'),
    ('potion_craft/img/portraits/humano-clerigo-3.png', 'Imagen 3'),
    # Agrega más imágenes aquí según sea necesario
]   
    GENERO = [
        ('masc', 'Masculino'),
        ('fem', 'Femenino')
    ]

    RAZA = [
        ('elfo', 'Elfo'),
        ('humano', 'Humano')
    ]

    AVATAR = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
       
    ]

    nombre = forms.CharField(label='Nombre')
    clase = forms.ChoiceField(choices=CLASES, label="¿Qué clase eres?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    
    genero = forms.ChoiceField(choices=GENERO, label="¿De qué género es tu personaje?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    raza = forms.ChoiceField(choices=RAZA, label="Elige tu raza",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    portrait = forms.ChoiceField(choices=AVATAR, label="Elige un avatar",
                                 widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = Personaje
        fields = ['nombre', 'clase', 'raza', 'genero', 'portrait']


class PotionForm(forms.Form):
    ESENCIAS = [
        ('0', 'Ninguna'),
        ('1', 'Esencia Volátil'),
        ('2', 'Esencia Acuosa'),
        ('3', 'Esencia Terrosa'), 
        ('4', 'Esencia Ígnea'),
    ]
    
    BASE = [
        ('0', 'Agua'),
        ('2', 'Agua destilada'),
        ('4', 'Aceite'), 
        ('6', 'Aceite esencial'),
        ('8', 'Agua bendita'),
        ('-2', 'Agua sucia'), 
        ('-4', 'Agua contaminada'),
        ('-6', 'Agua maldita'), 
    ]
    POTENCIADOR = [
        ('0', 'Sin alteraciones'), 
        ('1', 'Ingrediente corrupto'), 
        ('2', 'Ingrediente sospechoso'), 
    ]
    UTILES = [
        ('-5', 'Sin herramientas'), 
        ('-3', 'Kit de alquimia desgastado'), 
        ('0', 'Kit de alquimia básico'), 
        ('2', 'Kit de alquimia completo'), 
        ('4', 'Kit de maestro alquimista'),
        ('6', 'Laboratorio'),
    ]
    CONOCIMIENTOS = [
        ('-5', 'De memoria'), 
        ('0', 'Alquimia para principiantes'), 
        ('2', 'Manual de alquimia avanzado'), 
        ('4', 'Ars Alquimica'), 
        ('6', 'Gran grimorio de El Alquimista'), 
    ]
    CANTIDAD = [
        ('1', '1 esencia'), 
        ('2', '2 esencias'), 
        ('3', '3 esencias'), 
    ]
   
    esencia_1 = forms.ChoiceField(choices=ESENCIAS, 
                                 label="¿Qué esencia quieres usar?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    
    esencia_2 = forms.ChoiceField(choices=ESENCIAS, 
                                 label="¿Qué esencia quieres usar?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))

    base = forms.ChoiceField(choices=BASE, 
                                 label="¿Qué base líquida vas a usar para tu poción?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    
    alter = forms.ChoiceField(choices=POTENCIADOR, 
                                 label="¿Vas a alterar tu poción?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    
    conocimiento = forms.ChoiceField(choices=CONOCIMIENTOS, 
                                 label="¿Vas a alterar tu poción?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    
    util = forms.ChoiceField(choices=UTILES, 
                                 label="¿Vas a alterar tu poción?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    
    dado = forms.IntegerField(min_value = 0, initial=11)
   

    def __init__(self, *args, personaje=None, **kwargs):
        super().__init__(*args, **kwargs)
      
        for field in self.fields.values():
            field.error_messages['required'] = 'Acuérdate de elegir!'
    




class IngredienteForm(forms.Form):

    INGREDIENTES = [
        ('1', 'Raíz'),
        ('2', 'Hoja'),
        ('3', 'Tallo'),
        ('4', 'Flor'),
        ('5', 'Semilla'),
        ('6', 'Corteza'),
        ('7', 'Vulbo'),
        ('8', 'Micelio'),
    ]

    COLOR = [
        ('aire-fuego', 'Violeta'),
        ('aire', 'Azul'),
        ('agua-aire', 'Turquesa'),
        ('agua', 'Verde'),
        ('tierra-agua', 'Amarillo'),
        ('tierra', 'Marrón'),
        ('fuego-tierra', 'Naranja'),
        ('fuego', 'Rojo'),
    ]

    """
    A partir de aquí se podría hacer una condición:
    if "value del color" not in "value del procesamiento"... ¡Fail!
    else --- if 'aire' in 'valor del color' ... esencia obtenida += la qu ecorresponda.
    Es importante tener en cuenta que puedan salir hasta dos.
    """
    PROCESO = [
        ('aire', 'Fermentar'),
        ('fuego', 'Prender'),
        ('tierra', 'Secar'),
        ('agua', 'Destilar'),
    ]

    HERRAMIENTAS = [
        ('0', 'Cuchillo oxidado'),
        ('1', 'Manuscrito desfasado'),    
        ('2', 'Mortero'),                
        ('3', 'Cuchillo afilado'),        
        ('4', 'Libro de plantas'),         
    ]

    ingr = forms.ChoiceField(choices=INGREDIENTES, 
                                 label="Elige tus ingredientes",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    
    color = forms.ChoiceField(choices=COLOR, 
                                 label="¿Cómo es el ingrediente?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    
    proceso = forms.ChoiceField(choices=PROCESO, 
                                 label="¿Cómo vas a procesar el ingrediente?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    
    herramienta = forms.ChoiceField(choices=HERRAMIENTAS, 
                                 label="¿Qué herramientas tienes?",
                                 widget=forms.Select(attrs={'class': 'form-control'}))
    

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Cambiar el mensaje de required
        for field in self.fields.values():
            field.error_messages['required'] = ''

potion_craft/templates/potion_craft/borrar_datos_sesion.html
{% extends "potion_craft/layout.html" %}
{% load static %}
{% block body %}

<form action="{% url 'borrar_datos_sesion' %}" method="post">
    {% csrf_token %}
    <button type="submit">Borrar datos de sesión</button>
</form>


{% endblock %}

potion_craft/templates/potion_craft/character_creator.html
{% extends "potion_craft/layout.html" %}
{% load static %}
{% block body %}

<!-- HTML del formulario: En tu plantilla HTML, estás utilizando un formulario estándar 
    de HTML (<form method="post">). 
    Asegúrate de que el atributo name de los campos del formulario coincida
    con los nombres de los campos en tu modelo (nombre, clase, portrait).
         
    Si los nombres de los campos en el formulario no coinciden con los nombres
     de los campos en tu modelo, Django no podrá asignar los datos correctamente.
Además, dado que estás utilizando {{ form.as_p }} para renderizar los campos del formulario,
 Django manejará automáticamente la generación de los campos y sus atributos name correctamente. Sin embargo, es importante asegurarse de que el HTML generado sea correcto inspeccionando el código fuente de la página renderizada.
    
Si los nombres de los campos en el formulario HTML no coinciden
 con los nombres de los campos en tu modelo, podrías corregirlo usando los nombres de los campos del formulario que Django genera automáticamente. En lugar de definir manualmente los campos del formulario en tu plantilla, podrías usar {{ form.nombre }}, {{ form.clase }}, {{ form.portrait }} para renderizar cada campo individualmente. Esto garantizará que los nombres de los campos coincidan correctamente.
    
Si después de revisar estos aspectos todavía tienes problemas para guardar 
los datos en la base de datos, 
sería útil agregar impresiones de depuración en tu vista para verificar 
los datos que se están recibiendo en la petición POST. 

También puedes inspeccionar los mensajes de error que obtienes al validar 
el formulario para obtener más información sobre lo que podría estar causando el problema. -->



<div id="charcreator">

<h2>Crea tu personaje </h2>
<form method="post">
    {% csrf_token %}
    
    <label for="{{ id_nombre }}">Nombre: </label>
        <br>{{ form.nombre }} <br>

    <label for="id_clase">Clase:</label><br>
        {{ form.clase }}<br>

    <label for="id_raza">Raza:</label><br>
        {{ form.raza }}<br>

    <label for="id_genero">Género:</label>
        <br>{{ form.genero }}<br>

    <label for="id_portrait">Selecciona tu Avatar:</label>
        <br><div style="display: none;">{{ form.portrait }}</div><br>




    <div class="galeria">
        <button type="button" onclick="actualizarImagen()" value="-" class="button-74"> << </button>
        <div>
            <img src="{% static 'potion_craft/img/portraits/humano/masc-humano-guerrero-1.png' %}" alt="" class="galeria-side" id ="retrato-izquierda">
            <img src="{% static 'potion_craft/img/portraits/humano/masc-humano-guerrero-1.png' %}"  width="200px" id="retrato">
            <img src="{% static 'potion_craft/img/portraits/humano/masc-humano-guerrero-1.png' %}" alt="" class="galeria-side" id="retrato-derecha">
        </div>
        <button type="button" onclick="actualizarImagen()" value="+" class="button-74"> >> </button>
    </div>

    <br><br><button type="submit" class="button-74">Guardar</button>

    {% if form.errors %}
        <div class="errors">
            <ul>
                {% for field_errors in form.errors.values %}
                    {% for error in field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul> 
        </div>
    {% endif %}

</form>
</div>


{% endblock %}

potion_craft/templates/potion_craft/craft.html
{% extends "potion_craft/layout.html" %}
{% load static %}




{% block body %}


    <h2> Alquimia lab</h2>
    
    <form action="{% url 'potion_craft:craft' %}" method="post">
        {% csrf_token %}

        <h3> Preparación de ingredientes </h3>
        <br>
        <label for ="id_ingrediente"> Elige un ingrediente </label>
            <br>{{ form_ingrediente.ingr }}
        <br>
        

        <br>
        <label for = "id_color"> ¿Cómo es el ingrediente? </label>
            <br>{{ form_ingrediente.color }}
        <br>

        <br>
        <label for = "id_procesamiento"> Elige una forma de procesar el ingrediente </label>
            <br>{{ form_ingrediente.proceso }}
        <br>

        <br>
        <label for = "id_herramienta"> Elige una herramienta </label>
            <br>{{ form_ingrediente.herramienta }}<br>
        
        

        <input type="submit" value="Procesar tu ingrediente">
    


{% endblock %}

potion_craft/templates/potion_craft/index.html
{% extends "potion_craft/layout.html" %}
{% load static %}

<!----Recursos: 
    IMÁGENES Y SPRITES GRATIS: https://itch.io/search?q=potion+sprites
    HTML: https://getbootstrap.com/docs/5.3/getting-started/introduction/


-->

{% block body %}
    
    <span>Hola! 
        <br><span>Nombre de Usuario: {{ user_profile.user.username }}</span>
        <br><span>Nombre del perfil: {{ user_profile.nombre }}</span>
    </span>


    {% for personaje in listado_personajes %}
        <li> Personaje {{ personaje.nombre }}</li>
        <a href="{% url 'potion_craft:inventario_detail' personaje.id %}"> Página del personaje </a>
        
    {% empty %}
        <p>Nada</p>
    {% endfor %}

    <h2>Crea tu personaje </h2>
<form method="post">
    {% csrf_token %}
    
    <label for="{{ id_nombre }}">Nombre: </label>
        <br>{{ form.nombre }} <br>

    <label for="id_clase">Clase:</label><br>
        {{ form.clase }}<br>

    <label for="id_raza">Raza:</label><br>
        {{ form.raza }}<br>

    <label for="id_genero">Género:</label>
        <br>{{ form.genero }}<br>

    <label for="id_portrait">Selecciona tu Avatar:</label>
        <br><div style="display: none;">{{ form.portrait }}</div><br>




    <div class="galeria">
        <button type="button" onclick="actualizarImagen()" value="-" class="button-74"> << </button>
        <div>
            <img src="{% static 'potion_craft/img/portraits/humano/masc-humano-guerrero-1.png' %}" alt="" class="galeria-side" id ="retrato-izquierda">
            <img src="{% static 'potion_craft/img/portraits/humano/masc-humano-guerrero-1.png' %}"  width="200px" id="retrato">
            <img src="{% static 'potion_craft/img/portraits/humano/masc-humano-guerrero-1.png' %}" alt="" class="galeria-side" id="retrato-derecha">
        </div>
        <button type="button" onclick="actualizarImagen()" value="+" class="button-74"> >> </button>
    </div>

    <br><br><button type="submit" class="button-74">Guardar</button>

    {% if form.errors %}
        <div class="errors">
            <ul>
                {% for field_errors in form.errors.values %}
                    {% for error in field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                {% endfor %}
            </ul> 
        </div>
    {% endif %}

</form>
</div>

  
 
    

{% endblock %}

potion_craft/templates/potion_craft/inventario.html
{% extends "potion_craft/layout.html" %}
{% load static %}
{% block body %}

<p class="alerta">{{ alerta }}</p>

<h3>Inventario de Personajes de {{ usuario.nombre }}</h3>
{% for personaje in listado_personajes %}
    <li> {{ personaje.nombre }} ->
        <a href="{% url 'potion_craft:inventario_detail' personaje.id %}"> Inventario de personaje </a>
    </li>
{% endfor %}


<h3>Personaje: {{ personaje.nombre }} {{ personaje.id }}</h3>

<div class="grid-inventario">
    <div class="grid-item-1" style="text-align: top;">
        
        {{ personaje.nombre }}
        {{ personaje.clase }}
        {{ personaje.user_profile }}
        
    </div>
    <div class="grid-item-2">
        <img src="{% static personaje.portrait %}" width=100px>
        Hueco para esencias: {{ esencia }}
    </div>
    <div class="grid-item-3">
        Hueco para pociones: {{ pocion }}
    </div>
    <div>
        Hueco para ingredientes : {{ ingrediente }}
    </div>
</div>


{% endblock %}

potion_craft/templates/potion_craft/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="icon" href="{% static 'potion_craft/img/favicon.png' %}" type="img/favicon">
    <link rel="stylesheet" href="{% static 'potion_craft/style.css' %}">
    <link rel="stylesheet" href="{% static 'potion_craft/button.css' %}">
    <link href="{% static 'potion_craft/style-potion.css' %}" rel="stylesheet">

    <script src="{% static 'potion_craft/js/script.js' %}"></script>

</head>

<header>

       <!---LOGIN Y SIGN UP-->
       <div class="login">
        {% if user.is_authenticated %}
            Hi {{ user.username }} !
            <form action="{% url 'logout' %}" method="post">
                {% csrf_token %}
                <button type="submit">Log Out</button>
            </form>
        {% else %}
            <span>You are not logged in     | </span>
            <a href="{% url 'login' %}">Log In</a> or <a href="{% url 'accounts:signup' %}">Sign Up</a>
        {% endif %}
    </div>


         
    <ul class="menu">
        <li> <a href="{% url 'potion_craft:index' %}"> Home </a></li>
        <li> <a href="{% url 'potion_craft:craft' %}"> Ingredientes </a></li>
        <li> <a href="{% url 'potion_craft:potion' %}"> Pociones </a></li>  
        <li> <a href="{% url 'potion_craft:inventario' %}"> Inventario </a></li>
        <li> <a href="{% url 'potion_craft:character_creator' %}"> Crear Personaje </a></li> 
        
    </ul>

</header>

<!--- Lo que estamos haciendo con esto es decir que lo que viene a continuación 
    es lo que va a cambiar --->
<body>
    {% block body %}
    {% endblock %}
</body>

</html>

potion_craft/templates/potion_craft/perfil.html
{% extends "potion_craft/layout.html" %}
{% load static %}
{% block body %}

<h2>Inventario</h2>

<h1>Detalle del perfil de usuario</h1>
    <p>Nombre de usuario: {{ object.user.username }}</p>
    <p>Nombre: {{ object.nombre }}</p>
    <h2>Personajes:</h2>
    <ul>
        {% for personaje in personajes %}
            <li>{{ personaje.nombre }}</li>
        {% empty %}
            <li>No hay personajes asociados.</li>
        {% endfor %}
    </ul>

{% endblock %}

potion_craft/templates/potion_craft/potion copy.html
{% extends "potion_craft/layout.html" %}
{% load static %}
{% block body %}



</form>
  
    <h3>Esta segunda lista usa el request.session</h3>

    <ul style=" list-style-type: none;">
        {% for esencia in ingredientes %}
            <li class="listado">
                <b>Esencias obtenidas:</b> {{ esencia }}
            </li>
        {% empty %}
        <li>No hay esencias en este momento</li>
    {% endfor %}
    </ul>




    <h3> Potion Craft</h3>

    <form method="post">
        {% csrf_token %}
        <label for="id_esencias">Elige tu esencia:</label>
            <br>{{ form_potion.esencias }} <br>

        <label for="id_base">Elige tu base:</label>
            <br>{{ form_potion.base }}<br>
        
        <label for="id_potenciador">Y el ingrediente secreto es...</label>
            <br>{{ form_potion.alter }}<br>
        
        <label for="id_conocimiento">Un buen libro siempre ayuda:</label>
            <br>{{ form_potion.conocimiento }}<br>
        
        <label for="id_util">¿Has limpiado bien esa probeta?</label>
            <br>{{ form_potion.util }}<br>

        <label for="id_dado">El dado:</label>
            <br>{{ form_potion.dado }}<br>
       

        <input type="submit" value="Crear poción">
    </form>

    <li> <a href="{% url 'potion_craft:borrar' %}"> Borrar datos </a></li> 

{% endblock %}

potion_craft/templates/potion_craft/potion.html
{% extends "potion_craft/layout.html" %}
{% load static %}
{% block body %}

<script src="{% static 'potion_craft/js/potion.js' %}"></script>

</form>
    

    <h3>Inventario disponible de {{ personaje.nombre }}</h3>
    
    <img src="{% static personaje.portrait %}" width=100px>
    <div>
        {% if form_potion.errors %}
            <div class="alert alert-danger"  class="horizontal">
                {% for field, error_list in form_potion.errors.items %}
                    <ul>
                        {% for error in error_list %}
                            <li class="form_error">{{ error }}</li>
                        {% endfor %}
                    </ul>
                {% endfor %}
            </div>
        {% endif %}

        <ul style=" list-style-type: none;"  class="horizontal">
            {% for item in inventario.detalles_esencias %}
                <li class="listado">
                    <figure >
                        <img src="{% static 'potion_craft/img/ingr/esencia-' %}{{ item.valor }}.png" class = "esencia-pequeña">
                        <figcaption style="display:flex">
                            {{ item.nombre }} {{ item.cantidad }}
                        </figcaption style="display:flex">
                    </figure>
                </li>
            {% empty %}
                <li>No hay esencias en este momento</li>
            {% endfor %}
        </ul>
    </div>

    <div class="galeria">
        <img src="" alt="" id="img-esencia-1" class="esencia">
        <p> + </p>
        <img src="" alt="" id="img-esencia-2" class="esencia">
    </div>


    <h3> Potion Craft</h3>

    <form method="post">
        {% csrf_token %}
        <label for="id_esencias_1">Elige tu esencia:</label>
            <br>{{ form_potion.esencia_1 }} <br>
        
        <label for="id_esencias_1">Elige una segunda esencia:</label>
            <br>{{ form_potion.esencia_2 }} <br>


        <label for="id_base">Elige tu base:</label>
            <br>{{ form_potion.base }}<br>
        
        <label for="id_potenciador">Y el ingrediente secreto es...</label>
            <br>{{ form_potion.alter }}<br>
        
        <label for="id_conocimiento">Un buen libro siempre ayuda:</label>
            <br>{{ form_potion.conocimiento }}<br>
        
        <label for="id_util">¿Has limpiado bien esa probeta?</label>
            <br>{{ form_potion.util }}<br>

        <label for="id_dado">El dado:</label>
            <br>{{ form_potion.dado }}<br>
       

        <input type="submit" value="Crear poción">
    </form>

    <li> <a href="{% url 'potion_craft:borrar' %}"> Borrar datos </a></li> 


    
{% endblock %}